## https://fsymbols.com/generators/tarty/

#███╗░░░███╗░█████╗░██╗███╗░░██╗
#████╗░████║██╔══██╗██║████╗░██║
#██╔████╔██║███████║██║██╔██╗██║
#██║╚██╔╝██║██╔══██║██║██║╚████║
#██║░╚═╝░██║██║░░██║██║██║░╚███║
#╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝

name: Parkour
version: 1.0.0
build: 1
main: org.serversmc.parkour.core.Main
authors:
    - ServersMC
    - DennisLysenko
website: "" ## TODO - Update link
email: info@serversmc.org
description: "Add custom parkour courses with many effects, sounds, and a disappearing course to hide clutter"

#░█████╗░███╗░░░███╗██████╗░░██████╗
#██╔══██╗████╗░████║██╔══██╗██╔════╝
#██║░░╚═╝██╔████╔██║██║░░██║╚█████╗░
#██║░░██╗██║╚██╔╝██║██║░░██║░╚═══██╗
#╚█████╔╝██║░╚═╝░██║██████╔╝██████╔╝
#░╚════╝░╚═╝░░░░░╚═╝╚═════╝░╚═════╝░

commands:
    parkour:
        description: "Parkour Command"
        permission: "parkour"
        usage: "/parkour"
        aliases:
            - "pk"

#██████╗░███████╗██████╗░███╗░░░███╗░██████╗
#██╔══██╗██╔════╝██╔══██╗████╗░████║██╔════╝
#██████╔╝█████╗░░██████╔╝██╔████╔██║╚█████╗░
#██╔═══╝░██╔══╝░░██╔══██╗██║╚██╔╝██║░╚═══██╗
#██║░░░░░███████╗██║░░██║██║░╚═╝░██║██████╔╝
#╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═════╝░

permissions:
    #▒█▀▀▄ ▒█▀▀▀ ▒█▀▀▀ ░█▀▀█ ▒█░▒█ ▒█░░░ ▀▀█▀▀
    #▒█░▒█ ▒█▀▀▀ ▒█▀▀▀ ▒█▄▄█ ▒█░▒█ ▒█░░░ ░▒█░░
    #▒█▄▄▀ ▒█▄▄▄ ▒█░░░ ▒█░▒█ ░▀▄▄▀ ▒█▄▄█ ░▒█░░
    parkour: {}
    parkour.help: {}
    
    #░█▀▀█ ▒█▀▀▄ ▒█▀▄▀█ ▀█▀ ▒█▄░▒█
    #▒█▄▄█ ▒█░▒█ ▒█▒█▒█ ▒█░ ▒█▒█▒█
    #▒█░▒█ ▒█▄▄▀ ▒█░░▒█ ▄█▄ ▒█░░▀█
    parkour.admin:
        children: {}
    
    #░█▀▀█ ▒█░░░ ▒█░░░
    #▒█▄▄█ ▒█░░░ ▒█░░░
    #▒█░▒█ ▒█▄▄█ ▒█▄▄█
    parkour.*:
        children:
            - parkour
            - parkour.help
